### ISSUE TITLE
Camera crashes when flash used

### ISSUE THREAD

**Issue by Silic0nS0ldier** [jesec/android_device_samsung_herolte#2]
If there is a better place to report this, let me know. Just figured reporting it here is better than complaining about it in an overflowing XDA thread.

The issue has several, likely connected components.

1. The flash setting must be changed for it to trigger at all.
2. Flash is out of sync with camera capture.
3. When flash is used, an exception is raised.

The attached log should contain data covering all 3 issues (more or less in order).
[cameraConnectionLoss.txt](https://github.com/jesec/android_device_samsung_herolte/files/1631476/cameraConnectionLoss.txt)
Of note is that the flashlight works fine.

Even with this, the ROM is leaps and bounds ahead of stock. Feels like a brand new phone! So thanks for the effort in porting and maintaining this.

**Comment by jesec** [comment]
Please follow bug reporting guidances of LineageOS.

**Comment by Silic0nS0ldier** [comment]
This issue was with Resurrection Remix. You sure the LineageOS bug tracker is the right spot for this?

**Comment by jesec** [comment]
I am neither maintaining that nor responsible for that.

**Comment by Silic0nS0ldier** [comment]
Ah. I see. The last post on that thread does mention that. My bad.
